name: Git Bisect Workflow

on: [push, pull_request]

jobs:
  bisect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest  # Remplacez par les dépendances nécessaires

      - name: Run Git Bisect
        run: python myscript.py
